services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - 9999:8080
    command: "python -m src.api.main"

  bot:
    container_name: bot
    build:
      context: .
    command: "python -m src.bot.main"
